### ISSUE TITLE
Dependeny question

### ISSUE THREAD

**Issue by arno1979** [heimrichhannot/contao-email_voting#1]
I see that this package requires `contao-legacy/efg`. 
In a current project for which I could use `contao-email_voting` I am using [oneup/contao-efg](https://github.com/1up-lab/contao-efg) which also includes a bugfix concerning the use of the debug mode.
Would it be possible to satisfy the dependency with both packages or to change it to `oneup/contao-efg` as it seems to me to be the more current package?

Thanks!

**Comment by Defcon0** [comment]
Sounds like a good idea.

Could you please verify if both modules work together by installing oneup/contao-efg normally by composer and putting email_voting in your system/modules folder manually.

If everything works fine, I'll consider changing it in the core :-)

**Comment by arno1979** [comment]
Ok, great. I'll do as you described and then will get back to you.
Thanks again!

**Comment by arno1979** [comment]
I have installed the extension and quickly checked if it works with `oneup/contao-efg`.
Looks good to me. A few things I encountered:

- I had to regenerate the autoload files because the autoload.php included contained a different file path from the directory created when cloning the extension from GitHub
- In the instructions a step is missing: you have to activate the "Save formdata (efg)" option in the form properties for the activation to work properly. This is kind of obvious but when working from the instructions at first I didn't think about it but just followed it step by step without really thinking about it.

I didn't test the newsletter option because I don't have any newsletters in my current Contao installation but this really hasn't anything to do with efg anyway or am I wrong?

**Comment by Defcon0** [comment]
OK, I just added a new version 2.0.0 with the new dependency. Should be online in no time. Thanks for your support!

**Comment by arno1979** [comment]
Thanks for taking care of it so quickly!
