### ISSUE TITLE
Hook "validateVotingEmailFormField" is not executed

### ISSUE THREAD

**Issue by arno1979** [heimrichhannot/contao-email_voting#2]
Hey,

I just continued to play around with the voting extension and noticed that although I have defined a max number of 1 vote per e-mail I can vote as many times as I want with the same e-mail-address.
So I checked to see if the hook that should perform the check is being executed.
I added an extra line of code at the top of the function `validateVotingEmailFormField` in `EmailVoting.php`:
```php
\System::log('Test',__METHOD__,TL_GENERAL);
```
To my understanding this should send a message to the system log as soon as the function is called. This never happens. Adding a `die;` didn't have any effect as well.
Could you check this out?

Thanks
Arno

**Comment by Defcon0** [comment]
Mhm, the hook should work. Please have in mind that if you install a module via composer, in most cases classes are look up in the composer directory, i.e. in this case:

/composer/vendor/heimrichhannot/contao-email_voting/classes/EmailVoting

Please check this file if not already done.

**Comment by arno1979** [comment]
Ok, I didn't consider that. If the log statement is added to that file the message appears in the log file. But the problem of the max number of votes is of course still there.

**Comment by Defcon0** [comment]
Is the function now triggered in the other class? Do you have XDebug or some other debugger? Should be no problem to trace down the issue. Not much that can go wrong in that function ;-)

Unfortunately I'm shorton time at the moment, so help from my side could take some time :-(

**Comment by arno1979** [comment]
Update:
I looked at the if statement at the beginning of `validateVotingEmailFormField`.
When I replace
```php
if (($objForm = \FormModel::findBy('alias', str_replace('auto_', '', $intId))) !== null && $objForm->maxVoteCount)
```
with
```php
if (($objForm = \FormModel::findBy('alias', str_replace('auto_tl_', '', $intId))) !== null && $objForm->maxVoteCount)
```
it works.
I noticed that although my form alias is "publikumspreis" the variable $intId when echoed gives <del>"tl_auto_publikumspreis"</del> "auto_tl_publikumspreis" as output and therefore the $objForm was always empty.
What do you think?

**Comment by arno1979** [comment]
> Is the function now triggered in the other class?

Yes! See: https://github.com/heimrichhannot/contao-email_voting/issues/2#issuecomment-273508614

**Comment by Defcon0** [comment]
Ok, so is it tl_auto_... or auto_tl_? Your post contains both versions :-) Seems that the new efg fork works a bit different here

**Comment by arno1979** [comment]
It's `auto_tl_` actually. :) Sorry for the mixup.
Could you please double check if this is really the cause for the problem? I am not sure where the `auto_tl_` prefix is generated, I didn't look that deep into efg.

EDIT:
We need to be careful! Just to make sure I just changed the value for the field `formID`. That is the value used to fill `$intId`. In my case the value was `tl_publikumspreis` so that's where 'tl_' part comes from!
I think the problem is that in your if statement you are comparing the `alias` value with `$intId` which is filled not from the `alias` field of the form but the `formID` field.
To make the current statement work securely the values in both fields would always have to be identical. I think we'll need to change the if statement.
My proposition would be to change
```php
if (($objForm = \FormModel::findBy('alias', str_replace('auto_', '', $intId))) !== null && $objForm->maxVoteCount)
```
to
```php
if (($objForm = \FormModel::findBy('formID', str_replace('auto_', '', $intId))) !== null && $objForm->maxVoteCount)
```
But we'll need to thoroughly check if this works without any problems.
What do you think?

**Comment by Defcon0** [comment]
Did you try to remove existing formdata? I get fatal errors by this (which also had been a problem in the "original" efg). I opened a ticket:

https://github.com/1up-lab/contao-efg/issues/4

Besides that,I fixed the issue above. In fact, objForm is passed to the hook directly :-) So no need for searching it. Should work now.

**Comment by arno1979** [comment]
> Did you try to remove existing formdata? I get fatal errors by this (which also had been a problem in the "original" efg).

That's funny. I had no problems removing formdata. I have been doing this from the backend using the menu entry carrying the name of my form. I just tested this and there were no problems removing single entries or removing all entries using the "edit all" function.
Is that what you meant?

**Comment by Defcon0** [comment]
That's what I meant. Strange. Do you have the dca cache activated?

Did you test 2.0.1?

**Comment by arno1979** [comment]
The DCA cache was not active but I just turned it on to check. No problems either.
I was using 2.0.1, yes.

**Comment by Defcon0** [comment]
OK. With

> Did you test 2.0.1?

I meant, if you have tested the initial problem whether it's now solved for you?

**Comment by arno1979** [comment]
> I meant, if you have tested the initial problem whether it's now solved for you?

Oh, sorry, a little misunderstanding there. Yes, it did solve the problem. Thanks!
